name: Move Website Files to Root

on:
  push:
    branches:
      - master

jobs:
  move_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Move website files
        run: |
          shopt -s dotglob  # Include hidden files
          mv CAR_RENTALS/MUCHEDZI/* .
          mv CAR_RENTALS/MUCHEDZI/.gitignore .
          shopt -u dotglob  # Reset dotglob option
        working-directory: ${{ github.workspace }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Move website files to root folder"
          git push
