name: Move Website Content Up One Folder

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  move_content:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Move website content
        run: |
          mv CAR_RENTALS/MUCHEDZI/* .
          mv CAR_RENTALS/MUCHEDZI/.gitignore .
        working-directory: ${{ github.workspace }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Move website content to root folder"
          git push
